import type { Metadata } from "next";
import { AppFrame } from "@/components/product/app-frame";
import { SkillsBrowser } from "@/components/product/skills-browser";
import styles from "../product-page.module.css";

export const metadata: Metadata = {
  title: "Skills | Creator Skill Generator",
  description:
    "Browse persisted skill bundles generated by the backend, inspect their files, and download zip exports.",
};

const metrics = [
  { value: "Search", label: "filter by skill slug or file path" },
  { value: "Inspect", label: "open full bundle detail and file contents" },
  { value: "Export", label: "download existing zip archives from the backend" },
];

const managementNotes = [
  {
    endpoint: "GET /api/backend/v1/skills",
    detail: "Lists persisted bundles with file summaries and zip availability.",
  },
  {
    endpoint: "GET /api/backend/v1/skills/{name}",
    detail: "Loads full file contents for a single generated bundle.",
  },
  {
    endpoint: "GET /api/backend/v1/export/{name}/zip",
    detail: "Downloads the backend-created archive when it exists.",
  },
];

export default function SkillsPage() {
  return (
    <AppFrame currentPage="skills">
      <div className={styles.page}>
        <section className={styles.hero}>
          <div className={styles.heroCard}>
            <p className={styles.kicker}>Saved bundles</p>
            <h1 className={styles.title}>Browse what the backend already generated.</h1>
            <p className={styles.lead}>
              This view reads the current contents of the backend skill directory and turns
              them into a searchable library, so the frontend reflects real generated
              output instead of placeholder cards.
            </p>

            <div className={styles.metricGrid}>
              {metrics.map((metric) => (
                <div key={metric.label} className={styles.metricCard}>
                  <strong>{metric.value}</strong>
                  <span>{metric.label}</span>
                </div>
              ))}
            </div>
          </div>

          <aside className={styles.sideCard}>
            <p className={styles.kicker}>Management flow</p>
            <h2 className={styles.sideCardTitle}>What this page covers</h2>
            <p className={styles.sideCardLead}>
              Listing, drill-down, and export now live in the website instead of only in
              raw API calls.
            </p>

            <div className={styles.sideList}>
              {managementNotes.map((note) => (
                <div key={note.endpoint} className={styles.sideItem}>
                  <code>{note.endpoint}</code>
                  <span>{note.detail}</span>
                </div>
              ))}
            </div>
          </aside>
        </section>

        <section className={styles.content}>
          <SkillsBrowser />
        </section>
      </div>
    </AppFrame>
  );
}
